# Generated by Django 2.0.3 on 2018-03-11 18:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg_heart_rate', models.FloatField(blank=True, help_text='bmp', null=True)),
                ('avg_heart_rate_clock', models.FloatField(blank=True, help_text='bmp', null=True)),
                ('avg_speed', models.FloatField(blank=True, help_text='min/km', null=True)),
                ('max_heart_rate', models.IntegerField(blank=True, help_text='bmp', null=True)),
                ('max_heart_rate_clock', models.IntegerField(blank=True, help_text='bmp', null=True)),
                ('max_speed', models.FloatField(blank=True, help_text='min/km', null=True)),
                ('num_laps', models.IntegerField()),
                ('serial_number', models.CharField(max_length=255)),
                ('sport', models.CharField(max_length=255)),
                ('start_position_lat', models.FloatField(blank=True, help_text='deg', null=True)),
                ('start_position_long', models.FloatField(blank=True, help_text='deg', null=True)),
                ('start_time', models.DateTimeField()),
                ('timestamp', models.DateTimeField()),
                ('total_ascent', models.IntegerField(blank=True, help_text='m', null=True)),
                ('total_calories', models.IntegerField(blank=True, help_text='kcal', null=True)),
                ('total_descent', models.IntegerField(blank=True, help_text='m', null=True)),
                ('total_distance', models.FloatField(blank=True, help_text='m', null=True)),
                ('total_elapsed_time', models.FloatField(help_text='s')),
                ('total_timer_time', models.FloatField(help_text='s')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DataPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('altitude', models.FloatField(blank=True, help_text='m', null=True)),
                ('distance', models.FloatField(blank=True, help_text='m', null=True)),
                ('heart_rate', models.IntegerField(blank=True, help_text='bpm', null=True)),
                ('position_lat', models.FloatField(blank=True, help_text='deg', null=True)),
                ('position_long', models.FloatField(blank=True, help_text='deg', null=True)),
                ('speed', models.FloatField(blank=True, help_text='min/km', null=True)),
                ('timestamp', models.DateTimeField()),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='activities.Activity')),
            ],
        ),
        migrations.CreateModel(
            name='Lap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lap_nr', models.IntegerField()),
                ('avg_heart_rate', models.FloatField(blank=True, help_text='bmp', null=True)),
                ('avg_heart_rate_clock', models.IntegerField(blank=True, help_text='bmp', null=True)),
                ('avg_speed', models.FloatField(blank=True, help_text='min/km', null=True)),
                ('end_position_lat', models.FloatField(blank=True, help_text='deg', null=True)),
                ('end_position_long', models.FloatField(blank=True, help_text='deg', null=True)),
                ('end_time', models.DateTimeField()),
                ('lap_trigger', models.CharField(max_length=255)),
                ('max_heart_rate', models.IntegerField(blank=True, help_text='bmp', null=True)),
                ('max_heart_rate_clock', models.IntegerField(blank=True, help_text='bmp', null=True)),
                ('max_speed', models.FloatField(blank=True, help_text='min/km', null=True)),
                ('start_position_lat', models.FloatField(blank=True, help_text='deg', null=True)),
                ('start_position_long', models.FloatField(blank=True, help_text='deg', null=True)),
                ('start_time', models.DateTimeField()),
                ('timestamp', models.DateTimeField()),
                ('total_ascent', models.IntegerField(blank=True, help_text='m', null=True)),
                ('total_calories', models.IntegerField(blank=True, help_text='kcal', null=True)),
                ('total_descent', models.IntegerField(blank=True, help_text='m', null=True)),
                ('total_distance', models.FloatField(blank=True, help_text='m', null=True)),
                ('total_elapsed_time', models.FloatField(blank=True, help_text='s', null=True)),
                ('total_timer_time', models.FloatField(blank=True, help_text='s', null=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laps', to='activities.Activity')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='activity',
            unique_together={('serial_number', 'timestamp', 'user')},
        ),
    ]
